spring.application.name=ariscend-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ariscend_db
spring.datasource.username=postgres
spring.datasource.password=2213

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true