CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    due_date DATE,
    priority VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_tasks_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX idx_tasks_user_created_at ON tasks (user_id, created_at DESC);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(150),
    content TEXT NOT NULL DEFAULT '',
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_notes_user ON notes (user_id);
CREATE INDEX idx_notes_user_state_updated_at ON notes (user_id, archived, pinned, updated_at DESC);

CREATE TABLE habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(80),
    frequency VARCHAR(20) NOT NULL DEFAULT 'DAILY',
    target_days_per_week INTEGER NOT NULL DEFAULT 7,
    color VARCHAR(20),
    icon VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_habits_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_habits_frequency CHECK (frequency IN ('DAILY', 'WEEKLY')),
    CONSTRAINT chk_habits_target_days CHECK (target_days_per_week BETWEEN 1 AND 7)
);

CREATE INDEX idx_habits_user_active_created_at ON habits (user_id, is_active, created_at DESC);

CREATE TABLE habit_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id BIGINT NOT NULL,
    completed_date DATE NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR(1000),
    CONSTRAINT fk_habit_completions_habit FOREIGN KEY (habit_id) REFERENCES habits (id),
    CONSTRAINT uq_habit_completions_habit_date UNIQUE (habit_id, completed_date)
);

CREATE INDEX idx_habit_completions_habit_date ON habit_completions (habit_id, completed_date DESC);

CREATE TABLE transaction_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(80) NOT NULL,
    type VARCHAR(20) NOT NULL,
    system_defined BOOLEAN NOT NULL DEFAULT FALSE,
    system_key VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_categories_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_transaction_categories_system_key UNIQUE (system_key),
    CONSTRAINT chk_transaction_categories_type CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_transaction_categories_owner CHECK (
        (system_defined AND user_id IS NULL AND system_key IS NOT NULL)
        OR (NOT system_defined AND user_id IS NOT NULL AND system_key IS NULL)
    )
);

CREATE INDEX idx_transaction_categories_user ON transaction_categories (user_id);
CREATE INDEX idx_transaction_categories_available ON transaction_categories (active, type, system_defined, name);

CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    alias VARCHAR(80) NOT NULL,
    issuer VARCHAR(80) NOT NULL,
    type VARCHAR(20) NOT NULL,
    last_four_digits VARCHAR(4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    credit_limit NUMERIC(19, 2),
    opening_balance NUMERIC(19, 2),
    closing_day INTEGER,
    payment_due_day INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_cards_type CHECK (type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT chk_cards_last_four_digits CHECK (last_four_digits ~ '^[0-9]{4}$'),
    CONSTRAINT chk_cards_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_cards_credit_limit CHECK (credit_limit IS NULL OR credit_limit > 0),
    CONSTRAINT chk_cards_opening_balance CHECK (opening_balance IS NULL OR opening_balance >= 0),
    CONSTRAINT chk_cards_closing_day CHECK (closing_day IS NULL OR closing_day BETWEEN 1 AND 31),
    CONSTRAINT chk_cards_payment_due_day CHECK (payment_due_day IS NULL OR payment_due_day BETWEEN 1 AND 31),
    CONSTRAINT chk_cards_financial_fields CHECK (
        (type = 'CREDIT' AND credit_limit IS NOT NULL AND closing_day IS NOT NULL
            AND payment_due_day IS NOT NULL AND opening_balance IS NULL)
        OR (type = 'DEBIT' AND opening_balance IS NOT NULL AND credit_limit IS NULL
            AND closing_day IS NULL AND payment_due_day IS NULL)
    )
);

CREATE INDEX idx_cards_user_active_created_at ON cards (user_id, active, created_at DESC);

CREATE TABLE finance_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'MXN',
    payment_alert_days INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_finance_settings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_finance_settings_user UNIQUE (user_id),
    CONSTRAINT chk_finance_settings_currency CHECK (base_currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_finance_settings_alert_days CHECK (payment_alert_days BETWEEN 0 AND 30)
);

CREATE TABLE financial_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    target_amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    target_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_financial_goals_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_financial_goals_target_amount CHECK (target_amount > 0),
    CONSTRAINT chk_financial_goals_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_financial_goals_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_financial_goals_user_status_created_at
    ON financial_goals (user_id, status, created_at DESC);

CREATE TABLE financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    category_id BIGINT,
    card_id BIGINT,
    paid_credit_card_id BIGINT,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    exchange_rate NUMERIC(19, 6) NOT NULL,
    base_amount NUMERIC(19, 2) NOT NULL,
    description VARCHAR(500),
    transaction_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    goal_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_financial_transactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_financial_transactions_category FOREIGN KEY (category_id) REFERENCES transaction_categories (id),
    CONSTRAINT fk_financial_transactions_card FOREIGN KEY (card_id) REFERENCES cards (id),
    CONSTRAINT fk_financial_transactions_paid_card FOREIGN KEY (paid_credit_card_id) REFERENCES cards (id),
    CONSTRAINT chk_financial_transactions_type CHECK (type IN ('INCOME', 'EXPENSE', 'CREDIT_CARD_PAYMENT')),
    CONSTRAINT chk_financial_transactions_status CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT chk_financial_transactions_amount CHECK (amount > 0),
    CONSTRAINT chk_financial_transactions_exchange_rate CHECK (exchange_rate > 0),
    CONSTRAINT chk_financial_transactions_base_amount CHECK (base_amount >= 0),
    CONSTRAINT chk_financial_transactions_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_financial_transactions_relationships CHECK (
        (type = 'CREDIT_CARD_PAYMENT' AND category_id IS NULL AND paid_credit_card_id IS NOT NULL)
        OR (type IN ('INCOME', 'EXPENSE') AND category_id IS NOT NULL AND paid_credit_card_id IS NULL)
    )
);

CREATE INDEX idx_financial_transactions_user_date
    ON financial_transactions (user_id, transaction_date DESC);
CREATE INDEX idx_financial_transactions_user_status_type_date
    ON financial_transactions (user_id, status, type, transaction_date);
CREATE INDEX idx_financial_transactions_category ON financial_transactions (category_id);
CREATE INDEX idx_financial_transactions_card ON financial_transactions (card_id);
CREATE INDEX idx_financial_transactions_paid_card ON financial_transactions (paid_credit_card_id);

CREATE TABLE goal_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    exchange_rate NUMERIC(19, 6) NOT NULL,
    contribution_date DATE NOT NULL,
    notes VARCHAR(500),
    transaction_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_goal_contributions_goal FOREIGN KEY (goal_id) REFERENCES financial_goals (id),
    CONSTRAINT fk_goal_contributions_transaction FOREIGN KEY (transaction_id) REFERENCES financial_transactions (id),
    CONSTRAINT uq_goal_contributions_transaction UNIQUE (transaction_id),
    CONSTRAINT chk_goal_contributions_amount CHECK (amount > 0),
    CONSTRAINT chk_goal_contributions_exchange_rate CHECK (exchange_rate > 0),
    CONSTRAINT chk_goal_contributions_status CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

CREATE INDEX idx_goal_contributions_goal_date
    ON goal_contributions (goal_id, contribution_date DESC, created_at DESC);

INSERT INTO transaction_categories (name, type, system_defined, system_key, active)
VALUES
    ('Salario', 'INCOME', TRUE, 'INCOME_SALARY', TRUE),
    ('Trabajo independiente', 'INCOME', TRUE, 'INCOME_FREELANCE', TRUE),
    ('Ventas', 'INCOME', TRUE, 'INCOME_SALES', TRUE),
    ('Inversiones', 'INCOME', TRUE, 'INCOME_INVESTMENTS', TRUE),
    ('Regalos', 'INCOME', TRUE, 'INCOME_GIFTS', TRUE),
    ('Otros ingresos', 'INCOME', TRUE, 'INCOME_OTHER', TRUE),
    ('Alimentación', 'EXPENSE', TRUE, 'EXPENSE_FOOD', TRUE),
    ('Transporte', 'EXPENSE', TRUE, 'EXPENSE_TRANSPORT', TRUE),
    ('Vivienda', 'EXPENSE', TRUE, 'EXPENSE_HOUSING', TRUE),
    ('Servicios', 'EXPENSE', TRUE, 'EXPENSE_SERVICES', TRUE),
    ('Salud', 'EXPENSE', TRUE, 'EXPENSE_HEALTH', TRUE),
    ('Educación', 'EXPENSE', TRUE, 'EXPENSE_EDUCATION', TRUE),
    ('Entretenimiento', 'EXPENSE', TRUE, 'EXPENSE_ENTERTAINMENT', TRUE),
    ('Compras', 'EXPENSE', TRUE, 'EXPENSE_SHOPPING', TRUE),
    ('Metas y ahorro', 'EXPENSE', TRUE, 'EXPENSE_GOALS', TRUE),
    ('Otros gastos', 'EXPENSE', TRUE, 'EXPENSE_OTHER', TRUE)
ON CONFLICT (system_key) DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    system_defined = TRUE,
    user_id = NULL,
    active = TRUE;
